import {startCamera,stopCamera} from './camera.js';import {ToolDetector} from './detector.js';import {getRank} from './rank.js';import {loadLeaderboard,addLeaderboardEntry} from './leaderboard.js';
const LABELS=['allen_key_set','allen_key','screw_driver','hammer','cutters','pliers'];const TARGETS={screw_driver:'螺絲起子',pliers:'尖嘴鉗',cutters:'切割鉗'};const video=document.querySelector('#cameraVideo'),box=document.querySelector('#highlightBox'),status=document.querySelector('#statusLabel'),detectStatus=document.querySelector('#detectStatus');
const panels=Object.fromEntries(['idle','playing','success','nameEntry','leaderboard'].map(n=>[n,document.querySelector(`#${n}Panel`)]));let detector,stream=null,timer=null,busy=false,state='idle',target=null,locked=false,missing=0,started=0,lastSeconds=0;
function show(name){state=name;Object.entries(panels).forEach(([k,v])=>v.classList.toggle('hidden',k!==name));}function setBox(r){const host=document.querySelector('#cameraContainer').getBoundingClientRect(),vr=video.videoWidth/video.videoHeight,hr=host.width/host.height;let w,h,x,y;if(vr>hr){w=host.width;h=w/vr;x=0;y=(host.height-h)/2;}else{h=host.height;w=h*vr;y=0;x=(host.width-w)/2;}Object.assign(box.style,{left:`${x+r.x*w}px`,top:`${y+r.y*h}px`,width:`${r.w*w}px`,height:`${r.h*h}px`});box.classList.remove('hidden');}
async function init(){if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');detector=new ToolDetector({modelUrl:'models/tool_detector.onnx',labels:LABELS,confThreshold:.5});try{await detector.load();status.textContent='工具 YOLO 模型已就緒（本機推論）';}catch(e){status.textContent=`模型載入失敗：${e.message}`;document.querySelector('#startButton').disabled=true;}wire();show('idle');}
function wire(){document.querySelector('#startButton').onclick=startRound;document.querySelector('#cancelButton').onclick=toIdle;document.querySelector('#restartButton').onclick=toIdle;document.querySelector('#restartButton2').onclick=toIdle;document.querySelector('#enterNameButton').onclick=()=>show('nameEntry');document.querySelector('#confirmNameButton').onclick=saveName;document.querySelector('#nameInput').onkeydown=e=>{if(e.key==='Enter')saveName();};window.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&state==='idle'){e.preventDefault();startRound();}});}
async function startRound(){if(!stream){try{const result=await startCamera(video);stream=result.stream;document.querySelector('#cameraState').textContent='相機已啟動';}catch(e){status.textContent='相機啟動失敗，請允許攝影機權限。';return;}}target=Object.keys(TARGETS)[Math.floor(Math.random()*3)];locked=false;missing=0;started=performance.now();box.classList.add('hidden');document.querySelector('#promptLabel').textContent=`請拿取 ${TARGETS[target]}（尋找中…）`;document.querySelector('#cancelButton').classList.remove('hidden');show('playing');clearInterval(timer);timer=setInterval(tick,800);tick();}
async function tick(){if(busy||!detector?.session||state!=='playing')return;busy=true;document.querySelector('#timerLabel').textContent=`${((performance.now()-started)/1000).toFixed(2)} 秒`;try{const all=await detector.detect(video),match=all.filter(x=>x.label===target).sort((a,b)=>b.confidence-a.confidence)[0];if(match){locked=true;missing=0;setBox(match.box);document.querySelector('#promptLabel').textContent=`請拿取 ${TARGETS[target]}`;detectStatus.textContent=`YOLO 已鎖定 ${match.label}（${Math.round(match.confidence*100)}%）`;}else if(locked){if(++missing>=3)success();else detectStatus.textContent=`確認工具是否已拿走… ${missing}/3`;}else detectStatus.textContent='YOLO 尋找指定工具中…';}catch(e){detectStatus.textContent=`YOLO 推論失敗：${e.message}`;}finally{busy=false;}}
function success(){clearInterval(timer);lastSeconds=(performance.now()-started)/1000;box.classList.add('hidden');document.querySelector('#cancelButton').classList.add('hidden');document.querySelector('#successMainText').textContent=`完成！\n你只花了 ${lastSeconds.toFixed(2)} 秒`;document.querySelector('#successRankText').textContent=getRank(lastSeconds);show('success');}
function toIdle(){clearInterval(timer);box.classList.add('hidden');document.querySelector('#cancelButton').classList.add('hidden');if(stream){stopCamera(stream);stream=null;video.srcObject=null;document.querySelector('#cameraState').textContent='相機未啟動';}show('idle');}
function saveName(){const entries=addLeaderboardEntry(document.querySelector('#nameInput').value,lastSeconds);document.querySelector('#nameInput').value='';const list=document.querySelector('#leaderboardList');list.innerHTML=entries.length?entries.map((x,i)=>`<li>${i+1}. ${escape(x.name)}　${x.seconds.toFixed(2)}秒　${x.rank}</li>`).join(''):'<li>尚無紀錄</li>';show('leaderboard');}function escape(s){const e=document.createElement('span');e.textContent=s;return e.innerHTML;}init();
