/* Global ort is loaded before this module from lib/ort/ort.min.js. */
export class ToolDetector {
  constructor({modelUrl,labels,inputSize=640,confThreshold=.5,iouThreshold=.45}){Object.assign(this,{modelUrl,labels,inputSize,confThreshold,iouThreshold,session:null});}
  async load(){ort.env.wasm.numThreads=1;ort.env.wasm.wasmPaths='lib/ort/';this.session=await ort.InferenceSession.create(this.modelUrl,{executionProviders:['wasm']});}
  async detect(source){if(!this.session)return[];const sw=source.videoWidth||source.width,sh=source.videoHeight||source.height;if(!sw||!sh)return[];const {tensor,scale,padX,padY}=this.preprocess(source,sw,sh);const out=await this.session.run({[this.session.inputNames[0]]:tensor});return this.postprocess(out[this.session.outputNames[0]],scale,padX,padY,sw,sh);}
  preprocess(source,sw,sh){const n=this.inputSize,scale=Math.min(n/sw,n/sh),w=Math.round(sw*scale),h=Math.round(sh*scale),padX=Math.floor((n-w)/2),padY=Math.floor((n-h)/2);if(!this.canvas){this.canvas=document.createElement('canvas');this.canvas.width=this.canvas.height=n;this.ctx=this.canvas.getContext('2d',{willReadFrequently:true});}this.ctx.fillStyle='rgb(114,114,114)';this.ctx.fillRect(0,0,n,n);this.ctx.drawImage(source,0,0,sw,sh,padX,padY,w,h);const px=this.ctx.getImageData(0,0,n,n).data,a=new Float32Array(3*n*n),p=n*n;for(let i=0;i<p;i++){a[i]=px[i*4]/255;a[p+i]=px[i*4+1]/255;a[p*2+i]=px[i*4+2]/255;}return{tensor:new ort.Tensor('float32',a,[1,3,n,n]),scale,padX,padY};}
  postprocess(out,scale,padX,padY,sw,sh){const d=out.data,[,ch,anchors]=out.dims,classes=ch-4,c=[];for(let a=0;a<anchors;a++){let cls=-1,score=0;for(let k=0;k<classes;k++){const s=d[(4+k)*anchors+a];if(s>score){score=s;cls=k;}}if(score<this.confThreshold)continue;const cx=d[a],cy=d[anchors+a],w=d[anchors*2+a],h=d[anchors*3+a],x1=Math.max(0,(cx-w/2-padX)/scale),y1=Math.max(0,(cy-h/2-padY)/scale),x2=Math.min(sw,(cx+w/2-padX)/scale),y2=Math.min(sh,(cy+h/2-padY)/scale);c.push({cls,score,x1,y1,x2,y2});}return this.nms(c).map(x=>({label:this.labels[x.cls]||`class_${x.cls}`,confidence:x.score,box:{x:x.x1/sw,y:x.y1/sh,w:(x.x2-x.x1)/sw,h:(x.y2-x.y1)/sh}}));}
  nms(items){const out=[];for(const x of [...items].sort((a,b)=>b.score-a.score)){if(!out.some(y=>y.cls===x.cls&&this.iou(x,y)>this.iouThreshold))out.push(x);}return out;}
  iou(a,b){const w=Math.max(0,Math.min(a.x2,b.x2)-Math.max(a.x1,b.x1)),h=Math.max(0,Math.min(a.y2,b.y2)-Math.max(a.y1,b.y1)),u=(a.x2-a.x1)*(a.y2-a.y1)+(b.x2-b.x1)*(b.y2-b.y1)-w*h;return u?w*h/u:0;}
}
