/* Tool Dash: local-only PWA. YOLO/ONNX is used for target lock-on; no image leaves device. */
const TOOL_NAMES={screwdriver:'螺絲起子',needle_nose_pliers:'尖嘴鉗',wrench:'扳手'};
const COCO=['person','bicycle','car','motorcycle','airplane','bus','train','truck','boat','traffic light','fire hydrant','stop sign','parking meter','bench','bird','cat','dog','horse','sheep','cow','elephant','bear','zebra','giraffe','backpack','umbrella','handbag','tie','suitcase','frisbee','skis','snowboard','sports ball','kite','baseball bat','baseball glove','skateboard','surfboard','tennis racket','bottle','wine glass','cup','fork','knife','spoon','bowl','banana','apple','sandwich','orange','broccoli','carrot','hot dog','pizza','donut','cake','chair','couch','potted plant','bed','dining table','toilet','tv','laptop','mouse','remote','keyboard','cell phone','microwave','oven','toaster','sink','refrigerator','book','clock','vase','scissors','teddy bear','hair drier','toothbrush'];
const $=id=>document.getElementById(id), video=$('camera'), canvas=$('analysis'), ctx=canvas.getContext('2d',{willReadFrequently:true});
const ui={idle:$('idlePanel'),success:$('successPanel'),name:$('namePanel'),board:$('boardPanel'),prompt:$('prompt'),timer:$('timer'),box:$('targetBox'),result:$('result'),model:$('modelState'),camera:$('cameraState')};
let session=null, cameraReady=false, state='idle', target=null, targetRect=null, startedAt=0, tick=null, lostFrames=0, lastYoloAt=0, lastInference=null;
const MODEL='assets/yolov8n.onnx', CONFIDENCE=.35, BRIGHTNESS=48, MISSING_FRAMES=5;

function show(panel){[ui.idle,ui.success,ui.name,ui.board].forEach(p=>{p.hidden=p!==panel;p.classList.toggle('active',p===panel)});}
function message(text,kind=''){ui.result.textContent=text;ui.result.hidden=!text;ui.result.style.background=kind==='ok'?'#176d44e8':kind==='bad'?'#8a2525e8':'#132635e8';}
function rank(seconds){return seconds<=5?'閃電快手':seconds<=10?'工具專家':seconds<=15?'熟練技師':seconds<=20?'穩定挑戰者':seconds<=25?'新手上路':'持續練習';}
function frame(){if(!cameraReady)return false; canvas.width=video.videoWidth;canvas.height=video.videoHeight;ctx.drawImage(video,0,0,canvas.width,canvas.height);return true;}
function rectToScreen(r){const v=video.getBoundingClientRect(), scale=Math.max(v.width/canvas.width,v.height/canvas.height), w=canvas.width*scale,h=canvas.height*scale, ox=(v.width-w)/2,oy=(v.height-h)/2;ui.box.style.left=`${v.left+ox+r.x*w}px`;ui.box.style.top=`${v.top+oy+r.y*h}px`;ui.box.style.width=`${r.w*w}px`;ui.box.style.height=`${r.h*h}px`;}

async function startCamera(){try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=stream;await video.play();cameraReady=true;ui.camera.textContent='相機已啟動';$('startButton').disabled=false;message('相機已啟動，請放好工具');}catch(e){ui.camera.textContent='相機無法使用';message('請允許攝影機權限，再試一次','bad');}}
async function loadModel(){try{ort.env.wasm.wasmPaths='vendor/';ort.env.wasm.numThreads=1;session=await ort.InferenceSession.create(MODEL,{executionProviders:['wasm']});ui.model.textContent='YOLO ONNX Runtime Web 已就緒（本機推論）';}catch(e){ui.model.textContent='YOLO 模型載入失敗，將使用視覺 Demo 模式。';console.warn(e);}}

function foregroundBlobs(){if(!frame())return[];const W=96,H=54, img=ctx.getImageData(0,0,canvas.width,canvas.height).data, seen=new Uint8Array(W*H), blobs=[];const on=(x,y)=>{const px=Math.min(canvas.width-1,Math.round((x+.5)*canvas.width/W)),py=Math.min(canvas.height-1,Math.round((y+.5)*canvas.height/H)),i=(py*canvas.width+px)*4;return Math.max(img[i],img[i+1],img[i+2])>=BRIGHTNESS};for(let y=0;y<H;y++)for(let x=0;x<W;x++){let at=y*W+x;if(seen[at]||!on(x,y))continue;let stack=[[x,y]],n=0,minx=x,maxx=x,miny=y,maxy=y;seen[at]=1;while(stack.length){let[a,b]=stack.pop();n++;minx=Math.min(minx,a);maxx=Math.max(maxx,a);miny=Math.min(miny,b);maxy=Math.max(maxy,b);[[a+1,b],[a-1,b],[a,b+1],[a,b-1]].forEach(([nx,ny])=>{let ni=ny*W+nx;if(nx>=0&&nx<W&&ny>=0&&ny<H&&!seen[ni]&&on(nx,ny)){seen[ni]=1;stack.push([nx,ny])}})}if(n>W*H*.003)blobs.push({x:minx/W,y:miny/H,w:(maxx-minx+1)/W,h:(maxy-miny+1)/H,area:n/(W*H)});}return blobs.sort((a,b)=>b.area-a.area);}
function foregroundRatio(r){if(!frame())return 1;const x=Math.max(0,Math.floor(r.x*canvas.width)),y=Math.max(0,Math.floor(r.y*canvas.height)),w=Math.max(1,Math.floor(r.w*canvas.width)),h=Math.max(1,Math.floor(r.h*canvas.height)),d=ctx.getImageData(x,y,Math.min(w,canvas.width-x),Math.min(h,canvas.height-y)).data;let n=0;for(let i=0;i<d.length;i+=4)if(Math.max(d[i],d[i+1],d[i+2])>=BRIGHTNESS)n++;return n/(d.length/4);}

async function yolo(){if(!session||!frame())return null;const inputName=session.inputNames[0],shape=session.inputMetadata[inputName].dimensions,INPUT=Number(shape[2])||640;if(shape.length!==4)return null;const c=document.createElement('canvas');c.width=c.height=INPUT;const x=c.getContext('2d');x.drawImage(canvas,0,0,INPUT,INPUT);const p=x.getImageData(0,0,INPUT,INPUT).data,a=new Float32Array(3*INPUT*INPUT);for(let i=0;i<INPUT*INPUT;i++){a[i]=p[i*4]/255;a[i+INPUT*INPUT]=p[i*4+1]/255;a[i+2*INPUT*INPUT]=p[i*4+2]/255}const out=await session.run({[inputName]:new ort.Tensor('float32',a,[1,3,INPUT,INPUT])});const d=out[Object.keys(out)[0]].data,dims=out[Object.keys(out)[0]].dims;if(dims.length!==3)return null;let best=null;const channels=dims[1],count=dims[2];for(let i=0;i<count;i++){let cls=0,score=0;for(let c=4;c<channels;c++){const s=d[c*count+i];if(s>score){score=s;cls=c-4}}if(score>CONFIDENCE){const cx=d[i],cy=d[count+i],w=d[2*count+i],h=d[3*count+i];const r={x:(cx-w/2)/INPUT,y:(cy-h/2)/INPUT,w:w/INPUT,h:h/INPUT,label:COCO[cls]||`class ${cls}`,score};if(!best||r.score>best.score)best=r;}}return best;}

async function tryLock(){const now=performance.now();if(now-lastYoloAt>900){lastYoloAt=now;try{lastInference=await yolo();ui.model.textContent=lastInference?`YOLO 推論正常：${lastInference.label}（${Math.round(lastInference.score*100)}%）`:'YOLO 推論正常：本畫面未偵測到 COCO 類別物件。';}catch(e){console.warn(e);ui.model.textContent=`YOLO 推論失敗：${e.message||'未知錯誤'}`;}}const blobs=foregroundBlobs();const custom=lastInference&&TOOL_NAMES[lastInference.label]?lastInference:null;if(custom){targetRect=custom;message(`YOLO 已鎖定 ${TOOL_NAMES[custom.label]}（${Math.round(custom.score*100)}%）`,'ok');}else if(blobs[0]){targetRect=blobs[0];message(lastInference?`YOLO 偵測到 ${lastInference.label}，但此 Demo 模型沒有工具類別；已以視覺模式鎖定目標。`:'Demo 模式已鎖定目標；請將指定工具拿走。');}if(targetRect){rectToScreen(targetRect);ui.box.hidden=false;ui.prompt.textContent=`請拿取 ${TOOL_NAMES[target]}`;}}
function startGame(){if(!cameraReady)return startCamera();target=Object.keys(TOOL_NAMES)[Math.floor(Math.random()*3)];state='playing';targetRect=null;lostFrames=0;startedAt=performance.now();show(null);ui.box.hidden=true;ui.prompt.textContent=`請拿取 ${TOOL_NAMES[target]}（尋找中…）`;message('');clearInterval(tick);tick=setInterval(gameTick,180);}
async function gameTick(){if(state!=='playing')return;const elapsed=(performance.now()-startedAt)/1000;ui.timer.textContent=elapsed.toFixed(2);if(!targetRect){await tryLock();return}if(foregroundRatio(targetRect)<.08){if(++lostFrames>=MISSING_FRAMES)complete(elapsed)}else lostFrames=0;}
function complete(seconds){clearInterval(tick);state='success';ui.box.hidden=true;ui.prompt.textContent='';ui.timer.textContent=seconds.toFixed(2);$('successText').textContent=`你只花了 ${seconds.toFixed(2)} 秒`;$('rankText').textContent=rank(seconds);window.lastSeconds=seconds;show(ui.success);message('工具已離開鎖定區域！','ok');}
function toIdle(){clearInterval(tick);state='idle';ui.box.hidden=true;ui.prompt.textContent='準備好後，說「開始遊戲」';ui.timer.textContent='00.00';message('');show(ui.idle);}
function entries(){try{return JSON.parse(localStorage.getItem('toolDashScores')||'[]')}catch{return[]}}
function saveScore(){const name=$('nameInput').value.trim()||'匿名';const data=entries();data.push({name,seconds:window.lastSeconds,rank:rank(window.lastSeconds)});data.sort((a,b)=>a.seconds-b.seconds);localStorage.setItem('toolDashScores',JSON.stringify(data.slice(0,50)));renderBoard();}
function renderBoard(){const data=entries();$('leaderboard').innerHTML=data.length?data.map((e,i)=>`<li>${escapeHtml(e.name)}　${e.seconds.toFixed(2)}秒　${e.rank}</li>`).join(''):'<li>還沒有紀錄，當第一個挑戰者！</li>';show(ui.board);}
function escapeHtml(s){const t=document.createElement('span');t.textContent=s;return t.innerHTML}
function voice(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){message('此瀏覽器未提供 Web Speech 語音辨識。','bad');return}const r=new R();r.lang='zh-TW';r.interimResults=false;r.onresult=e=>handleCommand(e.results[0][0].transcript);r.onerror=()=>message('沒有聽清楚，請再說一次。','bad');r.start();}
function handleCommand(text){text=text.replace(/\s/g,'');message(`語音：${text}`);if(state==='name'){$('nameInput').value=text;return}if(/開始|遊戲/.test(text))startGame();else if(/取消/.test(text))toIdle();else if(/重新|再玩/.test(text))toIdle();else if(/檢查/.test(text)&&state==='playing'&&!targetRect)tryLock();}
$('cameraButton').onclick=startCamera;$('startButton').onclick=startGame;$('restartButton').onclick=toIdle;$('saveButton').onclick=()=>{state='name';show(ui.name)};$('confirmNameButton').onclick=saveScore;$('voiceNameButton').onclick=voice;$('playAgainButton').onclick=toIdle;
window.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!['INPUT'].includes(document.activeElement.tagName)){e.preventDefault();state==='idle'?startGame():state==='success'?toIdle():null}});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');loadModel();
